name: Pull Request Workflow
on: pull_request
jobs:
  pull-request-workflow:
    runs-on: ubuntu-slim
    steps:
      - name: Pull Request Workflow Step
        run: echo "Pull Request Workflow Step...."