[![Upload artifact](https://github.com/venkat-komarashetty/github-actions/actions/workflows/upload-artifact.yml/badge.svg?event=workflow_dispatch)](https://github.com/venkat-komarashetty/github-actions/actions/workflows/upload-artifact.yml)
name: Upload artifact
on: workflow_dispatch
jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Uploading artitfact
        uses: actions/upload-artifact@v4
        with:
          name: my-first-artifact
          path: artifact.txt
          retention-days: 10
